# Generated by Django 3.0.5 on 2020-12-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
    ]
